export const data = [
    {
        id: 1,
        link: 'https://i.postimg.cc/gcSKqxDs/IMG-2944.jpg',
        title: 'Bird Eggs',
        description: 'Fauna - From the Explorer journal - 2023',
    },
    {
        id: 2,
        link: 'https://i.postimg.cc/mgMKhv9Q/371258188-1082889416025682-1753913815915179920-n.jpg',
        title: 'Tropical Bliss',
        description: 'Journaling',
    },
    {
        id: 3,
        link: 'https://i.postimg.cc/cJL7PYdr/IMG-2770.jpg',
        title: 'Cabinet of Curiosities',
        description: 'Journaling',
    },
    {
        id: 4,
        link: 'https://i.postimg.cc/BQ5V0Tfg/ACS-0863.jpg',
        title: 'Seabirds',
        description: 'Journaling',
    },
    {
        id: 5,
        link: 'https://i.postimg.cc/YCCKDnLg/IMG-3797.jpg',
        title: 'Terrains',
        description: 'Journaling',
    },
    {
        id: 6,
        link: 'https://i.postimg.cc/bJ7S3S6D/404494167-7018615434913005-4866307232155881757-n.jpg',
        title: 'Whales',
        description: 'Journaling',
    },
    {
        id: 7,
        link: 'https://i.postimg.cc/fyV50dVV/IMG-7305.jpg',
        title: 'Traveller',
        description: 'Journaling',
    },
    {
        id: 8,
        link: 'https://i.postimg.cc/brd8Dm01/ACS-0737.jpg',
        title: 'The Man and the Horse',
        description: 'Journaling',
    },
    {
        id: 9,
        link: 'https://i.postimg.cc/GhCtSCjf/IMG-1361.jpg',
        title: 'Charles Darwin',
        description: 'Journaling',
    },
    {
        id: 10,
        link: 'https://i.postimg.cc/x8dHkVFg/IMG-7438.jpg',
        title: 'Le Cygne - Charles Baudelaire',
        description: 'Journaling',
    },
    {
        id: 11,
        link: 'https://i.postimg.cc/q73g5MW9/ACS-0768.jpg',
        title: 'Beekeeping',
        description: 'Journaling',
    },
    {
        id: 12,
        link: 'https://i.postimg.cc/cCVHsqqv/IMG-7437.jpg',
        title: 'Ornithology',
        description: 'Journaling',
    },
    {
        id: 13,
        link: 'https://i.postimg.cc/q73g5MW9/ACS-0768.jpg',
        title: '....',
        description: 'Journaling',
    },
    {
        id: 14,
        link: 'https://i.postimg.cc/5N2dtK90/IMG-2401.jpg',
        title: 'Butterflies #1',
        description: 'Journaling',
    },
    {
        id: 15,
        link: 'https://i.postimg.cc/Jhw2jp8j/IMG-2402.jpg',
        title: 'Butterflies #2',
        description: 'Journaling',
    },
    {
        id: 16,
        link: 'https://i.postimg.cc/pXbCGp4t/IMG-7445.jpg',
        title: 'Port Macquarie - Fishing Guide',
        description: 'Journaling',
    },
    {
        id: 17,
        link: 'https://i.postimg.cc/43sZkGTP/14.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 18,
        link: 'https://i.postimg.cc/jdfrD2xv/15.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 19,
        link: 'https://i.postimg.cc/pV4mNmcB/12.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 20,
        link: 'https://i.postimg.cc/W4545zJg/13.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 21,
        link: 'https://i.postimg.cc/PqDH0MJW/10.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 22,
        link: 'https://i.postimg.cc/pLwbQnCp/IMG-4039.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 23,
        link: 'https://i.postimg.cc/gJrTfzNf/CB551572-AEE3-4799-9-C4-D-E9-CF31-FA4940.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 24,
        link: 'https://i.postimg.cc/L6WrRZrN/7.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 25,
        link: 'https://i.postimg.cc/s2rHDPK9/8.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 26,
        link: 'https://i.postimg.cc/DzNg4qPM/IMG-4140.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 27,
        link: 'https://i.postimg.cc/767dpgZg/370288156-853670616101760-905481226313354488-n.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 28,
        link: 'https://i.postimg.cc/SKjJ7Kx0/358291717-1332222267408120-739172227589568352-n.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 29,
        link: 'https://i.postimg.cc/j5S0JWxN/IMG-7444.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 30,
        link: 'https://i.postimg.cc/yYV6yNLf/431866632-1128421594859681-3108921637041719801-n.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 31,
        link: 'https://i.postimg.cc/ydN7vdg2/1.jpg',
        title: 'Title dsjsjf',
        description: 'Journaling',
    },
    {
        id: 32,
        link: 'https://i.postimg.cc/DyPBp3Bn/IMG-0041.jpg',
        title: 'Title gjdjds',
        description: 'Journaling',
    },
    {
        id: 33,
        link: 'https://i.postimg.cc/Ssmf50kB/5.jpg',
        title: 'Title gjfkslsals fdjjsjshfh sksjf',
        description: 'Journaling',
    },
    {
        id: 34,
        link: 'https://i.postimg.cc/hjM1RCGf/6.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 35,
        link: 'https://i.postimg.cc/gk2Zd9GY/IMG-0878.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 36,
        link: 'https://i.postimg.cc/N0shCx1P/9.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 37,
        link: 'https://i.postimg.cc/pVqms0z3/11.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 38,
        link: 'https://i.postimg.cc/CK94TXR2/358622141-1017421985953017-1815112905744848271-n.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 39,
        link: 'https://i.postimg.cc/8cBBYLdt/314784843-811041206845177-2192839209036183741-n.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 40,
        link: 'https://i.postimg.cc/63KMX2L1/2.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 41,
        link: 'https://i.postimg.cc/43sZkGTP/14.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 42,
        link: 'https://i.postimg.cc/jdfrD2xv/15.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 43,
        link: 'https://i.postimg.cc/pV4mNmcB/12.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 44,
        link: 'https://i.postimg.cc/W4545zJg/13.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 45,
        link: 'https://i.postimg.cc/PqDH0MJW/10.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 46,
        link: 'https://i.postimg.cc/pLwbQnCp/IMG-4039.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 47,
        link: 'https://i.postimg.cc/gJrTfzNf/CB551572-AEE3-4799-9-C4-D-E9-CF31-FA4940.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 48,
        link: 'https://i.postimg.cc/L6WrRZrN/7.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 49,
        link: 'https://i.postimg.cc/s2rHDPK9/8.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 50,
        link: 'https://i.postimg.cc/DzNg4qPM/IMG-4140.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 51,
        link: 'https://i.postimg.cc/767dpgZg/370288156-853670616101760-905481226313354488-n.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 52,
        link: 'https://i.postimg.cc/SKjJ7Kx0/358291717-1332222267408120-739172227589568352-n.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 53,
        link: 'https://i.postimg.cc/j5S0JWxN/IMG-7444.jpg',
        title: 'Title',
        description: 'Journaling',
    },
    {
        id: 54,
        link: 'https://i.postimg.cc/yYV6yNLf/431866632-1128421594859681-3108921637041719801-n.jpg',
        title: 'Title',
        description: 'Journaling',
    },
  ]
  